# vim:ft=kitty

# The basic colors
foreground              #E8E8E8
background              #191919
selection_foreground    #232323
selection_background    #E8E8E8

# Cursor colors
cursor                  #A6A6A6
cursor_text_color       #D9D9D9

# URL underline color when hovering with mouse
url_color               #D9D9D9

# Kitty window border colors
active_border_color     #595959
inactive_border_color   #595959
bell_border_color       #595959

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #D9D9D9
active_tab_background   #262626
inactive_tab_foreground #D9D9D9
inactive_tab_background #262626
tab_bar_background      #D9D9D9

# Colors for marks (marked text in the terminal)
mark1_foreground #262626
mark1_background #404040
mark2_foreground #262626
mark2_background #262626
mark3_foreground #262626
mark3_background #A6A6A6

# The 16 terminal colors

# black
color0 #191919
color8 #191919

# red
color1 #fa456c
color9 #fa456c

# green
color2  #49bd7d
color10 #49bd7d

# yellow
color3  #eba86d
color11 #eba86d

# blue
color4  #7769fa
color12 #7769fa

# magenta
color5  #944edf
color13 #944edf

# cyan
color6  #387bdf
color14 #387bdf

# white
color7  #E8E8E8
color15 #E8E8E8
